scores = score.pdf # soprano.pdf alto.pdf tenor.pdf bass.pdf

#soprano.pdf :
#	lilypond soprano.ly

#alto.pdf : 
#	lilypond alto.ly

#tenor.pdf :
#	lilypond tenor.ly

#bass.pdf :
#	lilypond bass.ly

score.pdf :
	lilypond score.ly

all : $(scores)

clean : 
	rm *.pdf *.ps
